export const ghostTestFile: string = String.raw`<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:dc="http://purl.org/dc/elements/1.1/"
  xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom"
  version="2.0" xmlns:media="http://search.yahoo.com/mrss/">
  <channel>
    <title><![CDATA[CRTV DEV]]></title>
    <description><![CDATA[Web Development and Information Technology Articles for Creative Developers]]></description>
    <link>https://crtv.dev/</link>
    <image>
      <url>https://crtv.dev/favicon.png</url>
      <title>CRTV DEV</title>
      <link>https://crtv.dev/</link>
    </image>
    <generator>Ghost 5.75</generator>
    <lastBuildDate>Sat, 10 Feb 2024 19:21:44 GMT</lastBuildDate>
    <atom:link href="https://crtv.dev/rss/" rel="self" type="application/rss+xml" />
    <ttl>60</ttl>
    <item>
      <title><![CDATA[Cloudflare Magic Linker: Chrome Extension Project]]></title>
      <description><![CDATA[My journey of building a community Chrome extension to create deep links into the Cloudflare dashboard]]></description>
      <link>https://crtv.dev/cloudflare-magic-linker-chrome-extension-project/</link>
      <guid isPermaLink="false">65909d5256ab34be58786831</guid>
      <category><![CDATA[Chrome Extension]]></category>
      <category><![CDATA[Cloudflare]]></category>
      <category><![CDATA[Cloudflare Magic Linker]]></category>
      <category><![CDATA[Chrome Webstore]]></category>
      <category><![CDATA[Zero Trust]]></category>
      <category><![CDATA[Random]]></category>
      <category><![CDATA[Projects]]></category>
      <dc:creator><![CDATA[Mackenly Jones]]></dc:creator>
      <pubDate>Sat, 30 Dec 2023 23:43:42 GMT</pubDate>
      <media:content
        url="https://images.unsplash.com/photo-1515165562839-978bbcf18277?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDV8fHRyYWlufGVufDB8fHx8MTcwMzk3NjU2NHww&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=2000"
        medium="image" />
      <content:encoded><![CDATA[<img src="https://images.unsplash.com/photo-1515165562839-978bbcf18277?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDV8fHRyYWlufGVufDB8fHx8MTcwMzk3NjU2NHww&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=2000" alt="Cloudflare Magic Linker: Chrome Extension Project"><p>Beginning as a personal project, over Christmas, I decided to create a Chrome extension to make copying deep or magic links from the Cloudflare dashboard easier. In this post, I discuss the need for this tool, my process of building it, and how to install it yourself.</p>
<h2 id="what-are-magic-links">What Are &quot;Magic&quot; Links?</h2>
<p>The Cloudflare dashboard supports several deep link variables (affectionately known as magic links by the community) to make sharing links into the dashboard easier. These links work by replacing various IDs found within the dashboard&apos;s URLs with variables that are intercepted by the deep linker. When a user visits a link like in the example found below, they&apos;re shown a selection screen to choose the Cloudflare account they would like to use, then directed to select the zone they&apos;d like to use. </p>
<div class="kg-card kg-callout-card kg-callout-card-blue"><div class="kg-callout-emoji">&#x1F4A1;</div><div class="kg-callout-text">Read all about Accounts vs. Zones vs. Profiles <a href="https://crtv.dev/how-to-add-users-to-a-cloudflare-account/#:~:text=As%20a%20prerequisite%2C%20let%27s%20take%20a%20quick%20moment%20to%20look%20at%20three%20different%20Cloudflare%20terms%20that%20will%20be%20important%3A%20Zones%2C%20Profiles%2C%20and%20Accounts." rel="noreferrer">here</a>.</div></div>
<p>After making both selections, they&apos;re redirected, in this case, to the Zaraz tools configuration page.</p>
<pre><code>https://dash.cloudflare.com/?to=/:account/:zone/zaraz/tools-config/tools</code></pre>
<p>...converts into...</p>
<pre><code>https://dash.cloudflare.com/1234567890poiuytrewq/bogus.studio/zaraz/tools-config/tools</code></pre>
<p>This feature of the dashboard is extremely useful for sharing links in blog posts like this, helping others in GitHub issues or forums, or sharing links with coworkers. But before now, the only way to create them was to manually replace the values or to use a bot within the <a href="https://discord.gg/cloudflaredev?ref=crtv.dev">Cloudflare Discord community</a>.</p>
<h2 id="building-the-extension">Building the Extension</h2>
<p>I&apos;ve built several extensions before (mostly for removing ads on random sites and other random customizations that <a href="https://arc.net/?ref=crtv.dev">Arc</a> could probably replace), but never have I published one of the Chrome Webstore. The process itself isn&apos;t hard; you mostly just have to pay $5 to create a developer account and fill out some paperwork saying you&apos;re not loading remote code and that you&apos;re not doing anything sketchy with user data. </p>
<p>Still, the documentation leaves much to be desired. The manifest v3 migration, which I have heard lots of rumors suggesting is designed to make tools like adblockers less effective, seems to have caused a bit of chaos as far as documentation goes. The documentation is there, but it&apos;s hard to tell what version it&apos;s for; I found several broken links within Google&apos;s own help docs, and the general process feels chaotic. Thankfully, the actual functionality of my extension is relatively basic, with a <a href="https://github.com/mackenly/cloudflare-magic-linker/blob/main/manifest.json?ref=crtv.dev">simple manifest</a>, a small bit of <a href="https://github.com/mackenly/cloudflare-magic-linker/blob/main/src/popup.html?ref=crtv.dev">HTML </a>+ <a href="https://github.com/mackenly/cloudflare-magic-linker/blob/main/src/styles/popup.css?ref=crtv.dev">CSS</a>, and straightforward <a href="https://github.com/mackenly/cloudflare-magic-linker/blob/main/src/scripts/popup.js?ref=crtv.dev">JavaScript</a>.</p>
<pre><code class="language-Javascript">{
    &quot;manifest_version&quot;: 3,
    &quot;name&quot;: &quot;Cloudflare Magic Linker&quot;,
    &quot;version&quot;: &quot;1.0.0&quot;,
    &quot;description&quot;: &quot;Create magic deep links for the Cloudflare dashboard.&quot;,
    &quot;icons&quot;: {
        &quot;128&quot;: &quot;src/images/icon128.png&quot;
    },
    &quot;action&quot;: {
        &quot;default_popup&quot;: &quot;src/popup.html&quot;
    },
    &quot;host_permissions&quot;: [
        &quot;https://dash.cloudflare.com/*&quot;,
        &quot;https://one.dash.cloudflare.com/*&quot;
    ]
}</code></pre>
<p>I think the most challenging part was creating the extension&apos;s icon, but ChatGPT was able to come to the rescue and, on the first try, generated an icon that looked exactly as I wanted.</p>
<figure class="kg-card kg-image-card kg-card-hascaption"><img src="https://crtv.dev/content/images/2023/12/image.png" class="kg-image" alt="Cloudflare Magic Linker: Chrome Extension Project" loading="lazy" width="1920" height="992" srcset="https://crtv.dev/content/images/size/w600/2023/12/image.png 600w, https://crtv.dev/content/images/size/w1000/2023/12/image.png 1000w, https://crtv.dev/content/images/size/w1600/2023/12/image.png 1600w, https://crtv.dev/content/images/2023/12/image.png 1920w" sizes="(min-width: 720px) 720px"><figcaption><span style="white-space: pre-wrap;">ChatGPT Generating Icon</span></figcaption></figure>
<h2 id="community-feedback-and-collaboration">Community Feedback and Collaboration</h2>
<p>One of the most valuable parts of Cloudflare as a company is its community of users. After creating a quick MVP of the extension, I decided to make it public and ask the community for feedback and if anyone was aware of any more deep link variables that could be used (I don&apos;t think they&apos;re documented anywhere, at least publically). Within the community Discord, I <a href="https://discord.com/channels/595317990191398933/1190097743167893524?ref=crtv.dev">created a post</a> asking for feedback where several community members quickly added helpful comments and suggestions. A big shoutout to <a href="https://github.com/Cherry?ref=crtv.dev">James</a>, <a href="https://github.com/Tyler-OBrien?ref=crtv.dev">Chaika</a>, and <a href="https://github.com/Erisa?ref=crtv.dev">Erisa</a> for bringing up the <code>:pages-deployment</code> variable and that Zero Trust supports <code>:account</code>.</p>
<h2 id="using-the-extension">Using the Extension</h2>
<p>To try out the extension yourself, you can either install it from the <a href="https://chromewebstore.google.com/detail/fongdcpejhfehpdcahcjncgfhkepoico?ref=crtv.dev">Chrome Webstore</a> like a normal Chrome extension or load it unpacked from the source using developer mode by <a href="https://github.com/mackenly/cloudflare-magic-linker?ref=crtv.dev">cloning the repository</a> to your local machine. The source code is licensed under the <a href="https://github.com/mackenly/cloudflare-magic-linker/blob/main/LICENSE?ref=crtv.dev">GPL-3.0 license</a> and is open to issues and PRs.</p>
<figure class="kg-card kg-bookmark-card"><a class="kg-bookmark-container" href="https://chromewebstore.google.com/detail/fongdcpejhfehpdcahcjncgfhkepoico?ref=crtv.dev"><div class="kg-bookmark-content"><div class="kg-bookmark-title">Cloudflare Magic Linker</div><div class="kg-bookmark-description">Create magic deep links for the Cloudflare dashboard.</div><div class="kg-bookmark-metadata"><img class="kg-bookmark-icon" src="https://ssl.gstatic.com/chrome/webstore/images/icon_144px.png" alt="Cloudflare Magic Linker: Chrome Extension Project"><span class="kg-bookmark-author">Chrome Web Store</span></div></div><div class="kg-bookmark-thumbnail"><img src="https://lh3.googleusercontent.com/UPdc4DhIl_aTLbJCnlNefgYtTVTutW43Y5gg3sYY-4l9oSp1w9LTZalU5dzf6H0VU6doloseUNgAdmAFBlkIXEMV5Q=w128-h128-e365-rj-sc0x00ffffff" alt="Cloudflare Magic Linker: Chrome Extension Project"></div></a></figure>
<p>Once installed, simply go to a page within the Cloudflare dashboard or Zero Trust dashboard, click on the extension, and copy the link. I would recommend testing the link first. At the time of writing, support for magic links in Zero Trust isn&apos;t complete, and some pages in the regular dashboard, like Workers, don&apos;t have full support for deep links. I hope to update the extension in the future, if wider support is added to the magic link system by the Cloudflare team.</p>
<figure class="kg-card kg-image-card kg-card-hascaption"><img src="https://github.com/mackenly/cloudflare-magic-linker/blob/main/src/images/cloudflare-magic-linker-screenshot.png?raw=true" class="kg-image" alt="Cloudflare Magic Linker: Chrome Extension Project" loading="lazy"><figcaption><span style="white-space: pre-wrap;">Using the Extension to Copy and Link</span></figcaption></figure>
<p>If you&apos;ve found this post or extension valuable, I&apos;d love it if you <a href="https://github.com/mackenly/cloudflare-magic-linker?ref=crtv.dev">gave it a star</a>, and subscribed to my blog. In addition, you can <a href="https://github.com/sponsors/mackenly/?ref=crtv.dev">sponsor me on GitHub</a>, or get in touch about career opportunities on <a href="https://mackenly.com/?ref=crtv.dev">my personal site</a>. Thank you for reading this far, and happy coding! &#x1F525;</p>]]></content:encoded>
    </item>
    <item>
      <title><![CDATA[Review of Uptime Kuma Self-hosted Status Monitoring Tool]]></title>
      <description><![CDATA[Uptime monitoring is not just for large enterprises; it's an essential tool for anyone managing online services. Tools like Uptime Kuma democratize this capability, making it accessible and manageable for small teams and individual projects.]]></description>
      <link>https://crtv.dev/review-of-uptime-kuma-self-hosted-status-monitoring-tool/</link>
      <guid isPermaLink="false">654ed2d856ab34be58786718</guid>
      <category><![CDATA[Monitoring]]></category>
      <category><![CDATA[Cyber Security]]></category>
      <category><![CDATA[Observability]]></category>
      <category><![CDATA[Status Monitoring]]></category>
      <dc:creator><![CDATA[Mackenly Jones]]></dc:creator>
      <pubDate>Sat, 11 Nov 2023 06:20:34 GMT</pubDate>
      <media:content
        url="https://images.unsplash.com/photo-1494825514961-674db1ac2700?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDIwfHxmb3Jlc3R8ZW58MHx8fHwxNjk5NjY0NjQ0fDA&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=2000"
        medium="image" />
      <content:encoded><![CDATA[<img src="https://images.unsplash.com/photo-1494825514961-674db1ac2700?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDIwfHxmb3Jlc3R8ZW58MHx8fHwxNjk5NjY0NjQ0fDA&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=2000" alt="Review of Uptime Kuma Self-hosted Status Monitoring Tool"><p>Monitoring uptime statuses can be a complicated task, and SaaS services typically target enterprise users and have enterprise pricing. For small team and personal projects, uptime monitoring is often overlooked. Observability</p>
<p>Still, uptime monitoring is a valuable tool for incident response and tracking problems. If your servers go down at 2:00 AM on Saturday morning, it might be hard to catch unless you&apos;re a night owl like me. By the time you find out your critical service isn&apos;t functioning, it may be Monday or whenever customers or clients start sending support requests. That&apos;s no fun for anyone and makes it harder to gain visibility into what is broken.</p>
<p>That&apos;s where uptime monitoring tools come into play. A health check is run every few seconds or minutes to see if the server or endpoint is behaving as expected. The history of these checks and metrics on response speed is logged in a database for future review. If there&apos;s a problem, alarms or notifications can be triggered to ensure the right people know there&apos;s a problem as soon as it happens. </p>
<p>Tricities Media Group, my consultancy, is currently a single-person business, so I don&apos;t have a large team (or large budget) to configure enterprise monitoring solutions. But my client and my personal projects can still benefit from a comprehensive status monitoring system.</p>
<h2 id="my-solution">My Solution</h2>
<p>I decided upon a tool called Uptime Kuma, which is an open-source self-hosted monitoring tool that can be run with Docker. I&apos;m using Portainer on my Synology NAS to host the container and Cloudflare Zero Trust&apos;s Tunnels tool to securely expose it to the internet. This combo works great by using existing hardware that I already have running and allows for easy administration and maintenance. </p>
<p>Overall, I&apos;m super happy with how it&apos;s working and plan to expand my use of this tool in the future. This tool is open-source, MIT-licensed, and community-supported, so while there are a few potential cons, they are opportunities for improvement rather than complaints.</p>
<div class="kg-card kg-callout-card kg-callout-card-blue"><div class="kg-callout-emoji">&#x1F4A1;</div><div class="kg-callout-text"><a href="https://mariushosting.com/how-to-install-uptime-kuma-on-your-synology-nas/?ref=crtv.dev" rel="noreferrer">This tutorial by Marius Hosting</a> is an excellent resource for installing Uptime Kuma on Synologys. </div></div>
<h2 id="pros-of-uptime-kuma">Pros of Uptime Kuma</h2>
<ul><li>So. many. notification. options. This screenshot only shows about a quarter of the options. From Discord and Slack to Twilio and PagerTree, there are few notification tools that I can think of that don&apos;t exist. If, for some odd reason, the one you use isn&apos;t there, it also supports Webhooks with a custom body and headers, letting you send a request pretty much anywhere.</li></ul>
<figure class="kg-card kg-image-card"><img src="https://crtv.dev/content/images/2023/11/image.png" class="kg-image" alt="Review of Uptime Kuma Self-hosted Status Monitoring Tool" loading="lazy" width="481" height="524"></figure>
<ul><li>There are lots of options for customizing health check requests. You can change the HTTP method, encoding, body, headers, and specify authentication (basic auth, OAuth2, NTLM, and mTLS). With that many options, there&apos;s few things you can&apos;t do. You could even use it for HTTP CRONs.</li><li>A variety of check types. In addition to standard HTTP request and ping checks, there&apos;s also support for TCP, DNS, and other Docker containers. Many of these options support response validation to check if expected results are returned. One handy feature is a push URL that your application calls every x seconds. On top of that, there&apos;s support for a variety of database and server types, such as Postgres, MySQL, Radius, and MQTT.</li><li>The biggest feature for me is integration with Cloudflare Tunnels for reverse proxy. It&apos;s as easy as pasting in the tunnel token.</li><li>Status pages let you create custom statuses with groups of services you select. This allows for creating a status page for each client, for each application, or one for all of your applications. The sky is the limit. In addition, you can pin custom error or warning messages to highlight incident statuses as you correct any issues.</li><li>Custom domains for status pages. You can create custom domains for your status pages allowing for a single instance of Uptime Kuma to handle a variety of products and services.</li><li>If you run the tool on-prem like I&apos;m doing in your home or office you can setup checks for systems on your local network. This let&apos;s you ping computers, security cameras, or anything really to see if they&apos;re running and awake. This opens a lot of options and the potential for using statuses as triggers for automation. For example, if all of the office computers are offline and it&apos;s after hours, schedule the lights to turn off in 5 minutes. Or if the smart refrigerator stops responding to health checks it may be worth checking in on. Just an idea. &#x1F914;</li></ul>
<h2 id="cons-of-uptime-kuma">Cons of Uptime Kuma</h2>
<ul><li>The base page of the app directs to login rather than a status page. For example, when a user visits <a href="https://status.tricitiesmediagroup.com/?ref=crtv.dev">https://status.tricitiesmediagroup.com/</a> you would expect to be taken to a status page, but instead, you&apos;re taken to the status page admin login. A great change would be the ability to set a default status page to live at the app&apos;s base. A potential workaround for this is to host your app at a different URL and use custom domains for your status pages. This one might just be user error, but I&apos;d appreciate the option either way.</li><li>Creating an incident isn&apos;t intuitive, especially at first. To create an incident message/update, you have to go to the status page&apos;s editor as if you were changing the page&apos;s title or style. A dedicated page within the main dashboard would be more intuitive and feel like a more seamless solution. </li><li>Lack of REST HTTP API. An API would superpower the capabilities of this project and make things like incidents much more programmable. Being able to send updates directly from an incident management system or form would help make automation much more seamless.</li><li>Automation integrations. This is probably something held back by not having an API, but it would be great to see integrations with tools like n8n or Zapier to trigger automation outside of the existing notification destinations. This can kinda be done using the webhooks feature, but still, there&apos;s an opportunity to let automation tools do things like set maintenance windows and incident messages.</li></ul>
<h2 id="resiliency-and-disaster-readiness">Resiliency and Disaster Readiness</h2>
<p>To wrap up, I have to add a quick note about resiliency. Many companies have made the mistake of hosting their uptime monitoring and error visibility tooling with the same infrastructure dependencies as the services they monitor. It&apos;s easy to see how this can go wrong. If there&apos;s a major problem and your systems go down, it&apos;s likely your uptime monitor will go down as well, making it useless.</p>
<p>For my purposes, I&apos;m self-hosting it locally and using Cloudflare as the tunneling service. I, of course, do not host any of my services or sites locally, so as far as ISP, server, power, and network resiliency go, I should be fairly good. But I do use Cloudflare extensively. If Cloudflare&apos;s DNS or Tunneling went down, my entire infrastructure would be taken out. There are always going to be risks, but it&apos;s important to identify those risks and consider them when planning a solution. For my purposes, that&apos;s within my acceptable tolerance of risk, so I&apos;m not going to spend the resources required to go a different route. If you&apos;re a large company or a dependency in your infrastructure is less reliable or more critical, I would suggest getting as much separation as possible between your core application services and your uptime solution. (read: Host on a different continent, use a different DNS, a different domain name registrar, and use an alternative payment method to pay for it)</p>
<p>If you enjoyed this post or want to chat directly, let&apos;s connect on <a href="https://www.linkedin.com/in/mackenly?ref=crtv.dev">LinkedIn</a>, <a href="https://x.com/mackenlyjones?ref=crtv.dev">X/Twitter</a>, or contact me about business opportunities at <a href="https://tricitiesmediagroup.com/contact?ref=crtv.dev">tricitiesmediagroup.com/contact</a>.</p>]]></content:encoded>
    </item>
    <item>
      <title><![CDATA[The Ethics of Hourly Billing]]></title>
      <description><![CDATA[Is hourly billing ethical? How do employee incentives affect corporate bureaucracy?]]></description>
      <link>https://crtv.dev/the-ethics-of-hourly-billing/</link>
      <guid isPermaLink="false">64e6ab5c56ab34be58785782</guid>
      <category><![CDATA[Random]]></category>
      <category><![CDATA[Economics]]></category>
      <dc:creator><![CDATA[Mackenly Jones]]></dc:creator>
      <pubDate>Thu, 24 Aug 2023 02:33:49 GMT</pubDate>
      <media:content
        url="https://images.unsplash.com/photo-1556603235-0f484147fda4?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDI2fHxrYXJsJTIwbWFyeHxlbnwwfHx8fDE2OTI4Mzg4MDd8MA&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=2000"
        medium="image" />
      <content:encoded><![CDATA[<img src="https://images.unsplash.com/photo-1556603235-0f484147fda4?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDI2fHxrYXJsJTIwbWFyeHxlbnwwfHx8fDE2OTI4Mzg4MDd8MA&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=2000" alt="The Ethics of Hourly Billing"><p>One of the most obvious but often overlooked ethical conflicts within the workplace is workers who are paid hourly. By definition, those who are paid hourly get paid based on how many hours they work. (Indeed, 2023) It seems like a simple concept. But as information technology professionals, most of what we do involves making systems and processes more efficient. </p>
<p>But what does that mean if we&apos;re paid hourly? </p>
<p>Even if it might not seem that way, there is a finite amount of IT work that an organization can realistically need. So, by creating more efficient systems and processes, we&apos;re effectively reducing our earning potential even though we&apos;re adding value to the organization.&#xA0;</p>
<blockquote>There are downsides to being salaried as well, where a reduction of overall headcount may occur instead of a reduction of hours.</blockquote>
<p>Diving deeper, hourly billing is rooted in the Labor Theory of Value, a foundation of Marxism, where the value of labor is emphasized in the production process and ideal distribution of wealth. (Taylor, 1996) The idea that a worker&apos;s time is valuable is popularized by workers who argue they should be compensated based on how much time they spend working rather than the value they provide. This is where the concepts of minimum wages and pay ceilings come from. An example would be saying, &quot;Workers who work 60 hours per week should make more per year than those who work 40 hours because the 60-hour worker works harder.&quot;</p>
<figure class="kg-card kg-image-card kg-card-hascaption"><img src="https://images.unsplash.com/photo-1526688442562-41eb8259db9e?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDEwfHxjbG9jayUyMGlufGVufDB8fHx8MTY5MjgzOTE1NXww&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=2000" class="kg-image" alt="The Ethics of Hourly Billing" loading="lazy" width="2592" height="3888" srcset="https://images.unsplash.com/photo-1526688442562-41eb8259db9e?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDEwfHxjbG9jayUyMGlufGVufDB8fHx8MTY5MjgzOTE1NXww&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=600 600w, https://images.unsplash.com/photo-1526688442562-41eb8259db9e?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDEwfHxjbG9jayUyMGlufGVufDB8fHx8MTY5MjgzOTE1NXww&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=1000 1000w, https://images.unsplash.com/photo-1526688442562-41eb8259db9e?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDEwfHxjbG9jayUyMGlufGVufDB8fHx8MTY5MjgzOTE1NXww&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=1600 1600w, https://images.unsplash.com/photo-1526688442562-41eb8259db9e?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=M3wxMTc3M3wwfDF8c2VhcmNofDEwfHxjbG9jayUyMGlufGVufDB8fHx8MTY5MjgzOTE1NXww&amp;ixlib=rb-4.0.3&amp;q=80&amp;w=2400 2400w" sizes="(min-width: 720px) 720px"><figcaption><span>Photo by </span><a href="https://unsplash.com/@eiskonen?ref=crtv.dev"><span>Hans Eiskonen</span></a><span> / </span><a href="https://unsplash.com/?utm_source=ghost&amp;utm_medium=referral&amp;utm_campaign=api-credit"><span>Unsplash</span></a></figcaption></figure>
<p>By being a truly effective IT professional by providing the maximum value to your employer or client, you&apos;re optimizing yourself out of a job. So what&apos;s the alternative? Make things more complicated? Here are a few approaches that are taken:</p>
<ul><li>Put effort into developing complex and hard-to-understand policies, procedures, and guidelines to ensure that bureaucracy slows down the organization and increases the amount of required labor.</li><li>Increase the barrier of entry by requiring additional qualifications, certifications, government-mandated licenses, and other means to reduce and limit the talent pool.</li><li>Avoid tools that make us more efficient, such as modern IDEs (integrated development environments) and <a href="https://github.com/features/copilot?ref=crtv.dev">GitHub Copilot</a> (AI code autocomplete).</li><li>Unionize to pressure employers to let us increase the amount of time we spend by limiting change and innovation to protect union member jobs while increasing benefits and compensation.&#xA0;</li></ul>
<figure class="kg-card kg-image-card kg-card-hascaption"><img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.imgflip.com%2F1efqtj.jpg&amp;f=1&amp;nofb=1&amp;ipt=7d206e3dfa924505d4c62ef8504d60b2684f8647db89654e239ab02e6b9ad026&amp;ipo=images" class="kg-image" alt="The Ethics of Hourly Billing" loading="lazy"><figcaption><span>via imgflip</span></figcaption></figure>
<p>All of those options are commonly taken (not just in IT), but are they ethical? That question is answered based on your personal opinions and economic ideas. An alternative could be to incentivize employees to create value in a way that attempts to minimize the disincentivizing nature of increased efficiency and automation, but there are few mainstream examples of that within IT.</p>
<p>So that brings us to the title of this article: The Ethics of Hourly Billing</p>
<p>If employees aren&apos;t incentivized to be good at their jobs, that raises the question of how employees can behave ethically. I&apos;m of the persuasion that people never behave counter to their incentives, so to create an ethical workforce, hourly compensation can&apos;t be the sole motivator. </p>
<p>A few types of employees may include:</p>
<ul><li>Employees who see it as their moral duty to society to do their best at their jobs. </li><li>Those who simply do not consider the true economic incentives associated with their job. </li></ul>
<p>Most people probably fall within these two categories rather than maliciously sabotaging their workplace but likely do participate in activities that ensure their job security without even realizing it.</p>
<p>The traditional solution to this problem in the tech startup world is <a href="https://www.investopedia.com/terms/s/stockoption.asp?ref=crtv.dev">stock options</a> mirroring the long-standing practice of incentivizing executives by getting stock and/or full equity. When employees can earn favorable stock options, restricted stock, phantom stock, etc. they&apos;re given an opportunity to invest in their efforts and hopefully benefit from the profits of the company. But this doesn&apos;t necessarily make sense for every company (especially for small companies and those owned privately).</p>
<div class="kg-card kg-callout-card kg-callout-card-blue"><div class="kg-callout-emoji">&#x1F4B0;</div><div class="kg-callout-text">Startups are often messy. Sometimes the incentive to build a company up enough to be able to get an exit payday results in a sacrifice in quality control and security that ultimately hurts the startup&apos;s growth. Just giving employees stock probably isn&apos;t the answer either because that just incentivizes employees to work towards raising the company&apos;s valuation, which doesn&apos;t necessarily equal true business success.</div></div>
<p>So, what&apos;s the best solution to this ethical dilemma? I don&apos;t know. It&apos;s clear that employees whose roles are to minimize inefficiencies and to effectively automate their own jobs (and the jobs of others) aren&apos;t incentivized to act in the best interest of their company causing an ethics conflict. But it&apos;s not clear the best way to universally fix this issue. And complex hard-to-understand questions like this are why economists have job security. &#x1F609;&#x1F602;</p>
<hr>
<p>If you&apos;d like to read more on this topic, I wrote another post on hourly billing and labor theories over on The Church Factory, where I take a look at the similarities between traditional hourly billing and value-based pricing. Surprisingly, there are similarities, but also big differences. </p>
<figure class="kg-card kg-bookmark-card"><a class="kg-bookmark-container" href="https://thechurchfactory.com/value-pricing-vs-hourly-billing/?ref=crtv.dev"><div class="kg-bookmark-content"><div class="kg-bookmark-title">Value Pricing vs Hourly Billing</div><div class="kg-bookmark-description">If you&#x2019;re a freelancer or independent consultant pricing your services based on value is essential. However, there is a common theme among value pricing advocates that suggests hourly workers don&#x2019;t value price, which simply isn&#x2019;t true.</div><div class="kg-bookmark-metadata"><img class="kg-bookmark-icon" src="https://thechurchfactory.com/content/images/size/w256h256/2023/07/Logo-Red-Tiny-1.png" alt="The Ethics of Hourly Billing"><span class="kg-bookmark-author">The Church Factory</span><span class="kg-bookmark-publisher">Mackenly Jones</span></div></div><div class="kg-bookmark-thumbnail"><img src="https://images.unsplash.com/photo-1516201580490-33550d32de5c?crop=entropy&amp;cs=tinysrgb&amp;fit=max&amp;fm=jpg&amp;ixid=MnwxMTc3M3wwfDF8c2VhcmNofDR8fG9yYW5nZSUyMG1vbmV5fGVufDB8fHx8MTY0Njg0MzQ4MQ&amp;ixlib=rb-1.2.1&amp;q=80&amp;w=2000" alt="The Ethics of Hourly Billing"></div></a></figure>
<div class="kg-card kg-toggle-card" data-kg-toggle-state="close">
            <div class="kg-toggle-heading">
                <h4 class="kg-toggle-heading-text"><span>References</span></h4>
                <button class="kg-toggle-card-icon">
                    <svg id="Regular" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 24 24">
                        <path class="cls-1" d="M23.25,7.311,12.53,18.03a.749.749,0,0,1-1.06,0L.75,7.311"/>
                    </svg>
                </button>
            </div>
            <div class="kg-toggle-content"><p dir="ltr"><span>Indeed. (2023).&#xA0;</span><i><em class="italic">What Is an Hourly Employee and How Do Employers Pay Them?</em></i><span>&#xA0;Www.indeed.com; Indeed.&#xA0;</span><a href="https://www.indeed.com/career-advice/career-development/hourly-employee?ref=crtv.dev" target="_blank"><span>https://www.indeed.com/career-advice/career-development/hourly-employee</span></a> </p><p dir="ltr"><span>Taylor, K. S. (1996).&#xA0;</span><i><em class="italic">Human Society and the Global Economy</em></i><span>. www.d.umn.edu; University of Minnesota.&#xA0;</span><a href="https://www.d.umn.edu/cla/faculty/jhamlin/4111/2111-home/value.htm?ref=crtv.dev" target="_blank"><span>https://www.d.umn.edu/cla/faculty/jhamlin/4111/2111-home/value.htm</span></a> </p></div>
        </div>]]></content:encoded>
    </item>
  </channel>
</rss>`